/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BuilderRouteImport } from './routes/builder'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminVendorsRouteImport } from './routes/admin-vendors'
import { Route as AdminUsersRouteImport } from './routes/admin-users'
import { Route as AdminTrafficRouteImport } from './routes/admin-traffic'
import { Route as AdminSupportRouteImport } from './routes/admin-support'
import { Route as AdminShipmentsRouteImport } from './routes/admin-shipments'
import { Route as AdminSeoIntelligenceRouteImport } from './routes/admin-seo-intelligence'
import { Route as AdminSeedRouteImport } from './routes/admin-seed'
import { Route as AdminSecurityRouteImport } from './routes/admin-security'
import { Route as AdminSearchRouteImport } from './routes/admin-search'
import { Route as AdminReturnsRouteImport } from './routes/admin-returns'
import { Route as AdminReportsRouteImport } from './routes/admin-reports'
import { Route as AdminRegionRouteImport } from './routes/admin-region'
import { Route as AdminQualityRouteImport } from './routes/admin-quality'
import { Route as AdminProductsRouteImport } from './routes/admin-products'
import { Route as AdminPerformanceRouteImport } from './routes/admin-performance'
import { Route as AdminPaymentsRouteImport } from './routes/admin-payments'
import { Route as AdminOrdersOpsRouteImport } from './routes/admin-orders-ops'
import { Route as AdminOrdersRouteImport } from './routes/admin-orders'
import { Route as AdminNotificationsRouteImport } from './routes/admin-notifications'
import { Route as AdminMerchandisingRouteImport } from './routes/admin-merchandising'
import { Route as AdminMediaRouteImport } from './routes/admin-media'
import { Route as AdminMarketingMetricsRouteImport } from './routes/admin-marketing-metrics'
import { Route as AdminMarketingGrowthRouteImport } from './routes/admin-marketing-growth'
import { Route as AdminMarketingAutomationRouteImport } from './routes/admin-marketing-automation'
import { Route as AdminMarketingRouteImport } from './routes/admin-marketing'
import { Route as AdminLowStockRouteImport } from './routes/admin-low-stock'
import { Route as AdminLiveRouteImport } from './routes/admin-live'
import { Route as AdminInventoryIntelligenceRouteImport } from './routes/admin-inventory-intelligence'
import { Route as AdminInventoryRouteImport } from './routes/admin-inventory'
import { Route as AdminInboxPlacementRouteImport } from './routes/admin-inbox-placement'
import { Route as AdminFinancialRouteImport } from './routes/admin-financial'
import { Route as AdminExecutiveRouteImport } from './routes/admin-executive'
import { Route as AdminEmailsRouteImport } from './routes/admin-emails'
import { Route as AdminEmailQueueRouteImport } from './routes/admin-email-queue'
import { Route as AdminEmailOpsRouteImport } from './routes/admin-email-ops'
import { Route as AdminEmailHealthRouteImport } from './routes/admin-email-health'
import { Route as AdminEmailDeliveryRouteImport } from './routes/admin-email-delivery'
import { Route as AdminCustomersRouteImport } from './routes/admin-customers'
import { Route as AdminCustomerIntelligenceRouteImport } from './routes/admin-customer-intelligence'
import { Route as AdminCmsRouteImport } from './routes/admin-cms'
import { Route as AdminCategoriesRouteImport } from './routes/admin-categories'
import { Route as AdminBadgesBulkRouteImport } from './routes/admin-badges-bulk'
import { Route as AdminBadgesAnalyticsRouteImport } from './routes/admin-badges-analytics'
import { Route as AdminBadgesRouteImport } from './routes/admin-badges'
import { Route as AdminAnalyticsRouteImport } from './routes/admin-analytics'
import { Route as AdminAiOperationsRouteImport } from './routes/admin-ai-operations'
import { Route as AdminActivityRouteImport } from './routes/admin-activity'
import { Route as AdminAcquisitionIntelligenceRouteImport } from './routes/admin-acquisition-intelligence'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsTrendingRouteImport } from './routes/products.trending'
import { Route as ProductsNewArrivalsRouteImport } from './routes/products.new-arrivals'
import { Route as ProductsBestSellersRouteImport } from './routes/products.best-sellers'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PagesShippingRouteImport } from './routes/pages.shipping'
import { Route as PagesReturnsRouteImport } from './routes/pages.returns'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as HelpSellerAssistanceRouteImport } from './routes/help.seller-assistance'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminProductSlugRouteImport } from './routes/admin-product.$slug'
import { Route as AdminCustomersCustomerIdRouteImport } from './routes/admin-customers.$customerId'
import { Route as AccountSupportRouteImport } from './routes/account_.support'
import { Route as AccountSecurityRouteImport } from './routes/account_.security'
import { Route as AccountReturnsRouteImport } from './routes/account_.returns'
import { Route as AccountProfileRouteImport } from './routes/account_.profile'
import { Route as AccountPreferencesRouteImport } from './routes/account_.preferences'
import { Route as AccountPaymentsRouteImport } from './routes/account_.payments'
import { Route as AccountOrdersRouteImport } from './routes/account_.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account_.notifications'
import { Route as AccountHistoryRouteImport } from './routes/account_.history'
import { Route as AccountAddressesRouteImport } from './routes/account_.addresses'
import { Route as AdminProductSlugIndexRouteImport } from './routes/admin-product.$slug.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as CategoryMainSubRouteImport } from './routes/category.$main.$sub'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicExpireOrdersRouteImport } from './routes/api/public/expire-orders'
import { Route as AdminProductSlugShippingRouteImport } from './routes/admin-product.$slug.shipping'
import { Route as AdminProductSlugSeoRouteImport } from './routes/admin-product.$slug.seo'
import { Route as AdminProductSlugReturnsRouteImport } from './routes/admin-product.$slug.returns'
import { Route as AdminProductSlugPricingRouteImport } from './routes/admin-product.$slug.pricing'
import { Route as AdminProductSlugPreviewRouteImport } from './routes/admin-product.$slug.preview'
import { Route as AdminProductSlugMerchandisingRouteImport } from './routes/admin-product.$slug.merchandising'
import { Route as AdminProductSlugInventoryRouteImport } from './routes/admin-product.$slug.inventory'
import { Route as AdminProductSlugDetailsRouteImport } from './routes/admin-product.$slug.details'
import { Route as AdminProductSlugAnalyticsRouteImport } from './routes/admin-product.$slug.analytics'
import { Route as AccountPaymentMethodsAddRouteImport } from './routes/account_.payment-methods.add'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksCourierRouteImport } from './routes/api/public/webhooks/$courier'
import { Route as ApiPublicTrackOpenRouteImport } from './routes/api/public/track.open'
import { Route as ApiPublicTrackClickRouteImport } from './routes/api/public/track.click'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRoute = BuilderRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVendorsRoute = AdminVendorsRouteImport.update({
  id: '/admin-vendors',
  path: '/admin-vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrafficRoute = AdminTrafficRouteImport.update({
  id: '/admin-traffic',
  path: '/admin-traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/admin-support',
  path: '/admin-support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/admin-shipments',
  path: '/admin-shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoIntelligenceRoute = AdminSeoIntelligenceRouteImport.update({
  id: '/admin-seo-intelligence',
  path: '/admin-seo-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeedRoute = AdminSeedRouteImport.update({
  id: '/admin-seed',
  path: '/admin-seed',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSecurityRoute = AdminSecurityRouteImport.update({
  id: '/admin-security',
  path: '/admin-security',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/admin-search',
  path: '/admin-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/admin-returns',
  path: '/admin-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin-reports',
  path: '/admin-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRegionRoute = AdminRegionRouteImport.update({
  id: '/admin-region',
  path: '/admin-region',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQualityRoute = AdminQualityRouteImport.update({
  id: '/admin-quality',
  path: '/admin-quality',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin-products',
  path: '/admin-products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPerformanceRoute = AdminPerformanceRouteImport.update({
  id: '/admin-performance',
  path: '/admin-performance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin-payments',
  path: '/admin-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersOpsRoute = AdminOrdersOpsRouteImport.update({
  id: '/admin-orders-ops',
  path: '/admin-orders-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin-orders',
  path: '/admin-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin-notifications',
  path: '/admin-notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMerchandisingRoute = AdminMerchandisingRouteImport.update({
  id: '/admin-merchandising',
  path: '/admin-merchandising',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/admin-media',
  path: '/admin-media',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingMetricsRoute = AdminMarketingMetricsRouteImport.update({
  id: '/admin-marketing-metrics',
  path: '/admin-marketing-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingGrowthRoute = AdminMarketingGrowthRouteImport.update({
  id: '/admin-marketing-growth',
  path: '/admin-marketing-growth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingAutomationRoute =
  AdminMarketingAutomationRouteImport.update({
    id: '/admin-marketing-automation',
    path: '/admin-marketing-automation',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/admin-marketing',
  path: '/admin-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLowStockRoute = AdminLowStockRouteImport.update({
  id: '/admin-low-stock',
  path: '/admin-low-stock',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin-live',
  path: '/admin-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryIntelligenceRoute =
  AdminInventoryIntelligenceRouteImport.update({
    id: '/admin-inventory-intelligence',
    path: '/admin-inventory-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin-inventory',
  path: '/admin-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInboxPlacementRoute = AdminInboxPlacementRouteImport.update({
  id: '/admin-inbox-placement',
  path: '/admin-inbox-placement',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/admin-financial',
  path: '/admin-financial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminExecutiveRoute = AdminExecutiveRouteImport.update({
  id: '/admin-executive',
  path: '/admin-executive',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/admin-emails',
  path: '/admin-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailQueueRoute = AdminEmailQueueRouteImport.update({
  id: '/admin-email-queue',
  path: '/admin-email-queue',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailOpsRoute = AdminEmailOpsRouteImport.update({
  id: '/admin-email-ops',
  path: '/admin-email-ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailHealthRoute = AdminEmailHealthRouteImport.update({
  id: '/admin-email-health',
  path: '/admin-email-health',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEmailDeliveryRoute = AdminEmailDeliveryRouteImport.update({
  id: '/admin-email-delivery',
  path: '/admin-email-delivery',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin-customers',
  path: '/admin-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomerIntelligenceRoute =
  AdminCustomerIntelligenceRouteImport.update({
    id: '/admin-customer-intelligence',
    path: '/admin-customer-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin-cms',
  path: '/admin-cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin-categories',
  path: '/admin-categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBadgesBulkRoute = AdminBadgesBulkRouteImport.update({
  id: '/admin-badges-bulk',
  path: '/admin-badges-bulk',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBadgesAnalyticsRoute = AdminBadgesAnalyticsRouteImport.update({
  id: '/admin-badges-analytics',
  path: '/admin-badges-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBadgesRoute = AdminBadgesRouteImport.update({
  id: '/admin-badges',
  path: '/admin-badges',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAiOperationsRoute = AdminAiOperationsRouteImport.update({
  id: '/admin-ai-operations',
  path: '/admin-ai-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin-activity',
  path: '/admin-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAcquisitionIntelligenceRoute =
  AdminAcquisitionIntelligenceRouteImport.update({
    id: '/admin-acquisition-intelligence',
    path: '/admin-acquisition-intelligence',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsTrendingRoute = ProductsTrendingRouteImport.update({
  id: '/products/trending',
  path: '/products/trending',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsNewArrivalsRoute = ProductsNewArrivalsRouteImport.update({
  id: '/products/new-arrivals',
  path: '/products/new-arrivals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsBestSellersRoute = ProductsBestSellersRouteImport.update({
  id: '/products/best-sellers',
  path: '/products/best-sellers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesShippingRoute = PagesShippingRouteImport.update({
  id: '/pages/shipping',
  path: '/pages/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesReturnsRoute = PagesReturnsRouteImport.update({
  id: '/pages/returns',
  path: '/pages/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSellerAssistanceRoute = HelpSellerAssistanceRouteImport.update({
  id: '/seller-assistance',
  path: '/seller-assistance',
  getParentRoute: () => HelpRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AdminProductSlugRoute = AdminProductSlugRouteImport.update({
  id: '/admin-product/$slug',
  path: '/admin-product/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersCustomerIdRoute =
  AdminCustomersCustomerIdRouteImport.update({
    id: '/$customerId',
    path: '/$customerId',
    getParentRoute: () => AdminCustomersRoute,
  } as any)
const AccountSupportRoute = AccountSupportRouteImport.update({
  id: '/account_/support',
  path: '/account/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account_/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/account_/returns',
  path: '/account/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account_/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/account_/preferences',
  path: '/account/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/account_/payments',
  path: '/account/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account_/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account_/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/account_/history',
  path: '/account/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account_/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductSlugIndexRoute = AdminProductSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductSlugRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryMainSubRoute = CategoryMainSubRouteImport.update({
  id: '/category/$main/$sub',
  path: '/category/$main/$sub',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExpireOrdersRoute = ApiPublicExpireOrdersRouteImport.update({
  id: '/api/public/expire-orders',
  path: '/api/public/expire-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductSlugShippingRoute =
  AdminProductSlugShippingRouteImport.update({
    id: '/shipping',
    path: '/shipping',
    getParentRoute: () => AdminProductSlugRoute,
  } as any)
const AdminProductSlugSeoRoute = AdminProductSlugSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminProductSlugRoute,
} as any)
const AdminProductSlugReturnsRoute = AdminProductSlugReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AdminProductSlugRoute,
} as any)
const AdminProductSlugPricingRoute = AdminProductSlugPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AdminProductSlugRoute,
} as any)
const AdminProductSlugPreviewRoute = AdminProductSlugPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AdminProductSlugRoute,
} as any)
const AdminProductSlugMerchandisingRoute =
  AdminProductSlugMerchandisingRouteImport.update({
    id: '/merchandising',
    path: '/merchandising',
    getParentRoute: () => AdminProductSlugRoute,
  } as any)
const AdminProductSlugInventoryRoute =
  AdminProductSlugInventoryRouteImport.update({
    id: '/inventory',
    path: '/inventory',
    getParentRoute: () => AdminProductSlugRoute,
  } as any)
const AdminProductSlugDetailsRoute = AdminProductSlugDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => AdminProductSlugRoute,
} as any)
const AdminProductSlugAnalyticsRoute =
  AdminProductSlugAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AdminProductSlugRoute,
  } as any)
const AccountPaymentMethodsAddRoute =
  AccountPaymentMethodsAddRouteImport.update({
    id: '/account_/payment-methods/add',
    path: '/account/payment-methods/add',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksCourierRoute =
  ApiPublicWebhooksCourierRouteImport.update({
    id: '/api/public/webhooks/$courier',
    path: '/api/public/webhooks/$courier',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTrackOpenRoute = ApiPublicTrackOpenRouteImport.update({
  id: '/api/public/track/open',
  path: '/api/public/track/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTrackClickRoute = ApiPublicTrackClickRouteImport.update({
  id: '/api/public/track/click',
  path: '/api/public/track/click',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-acquisition-intelligence': typeof AdminAcquisitionIntelligenceRoute
  '/admin-activity': typeof AdminActivityRoute
  '/admin-ai-operations': typeof AdminAiOperationsRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-badges': typeof AdminBadgesRoute
  '/admin-badges-analytics': typeof AdminBadgesAnalyticsRoute
  '/admin-badges-bulk': typeof AdminBadgesBulkRoute
  '/admin-categories': typeof AdminCategoriesRoute
  '/admin-cms': typeof AdminCmsRoute
  '/admin-customer-intelligence': typeof AdminCustomerIntelligenceRoute
  '/admin-customers': typeof AdminCustomersRouteWithChildren
  '/admin-email-delivery': typeof AdminEmailDeliveryRoute
  '/admin-email-health': typeof AdminEmailHealthRoute
  '/admin-email-ops': typeof AdminEmailOpsRoute
  '/admin-email-queue': typeof AdminEmailQueueRoute
  '/admin-emails': typeof AdminEmailsRoute
  '/admin-executive': typeof AdminExecutiveRoute
  '/admin-financial': typeof AdminFinancialRoute
  '/admin-inbox-placement': typeof AdminInboxPlacementRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-inventory-intelligence': typeof AdminInventoryIntelligenceRoute
  '/admin-live': typeof AdminLiveRoute
  '/admin-low-stock': typeof AdminLowStockRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-marketing-automation': typeof AdminMarketingAutomationRoute
  '/admin-marketing-growth': typeof AdminMarketingGrowthRoute
  '/admin-marketing-metrics': typeof AdminMarketingMetricsRoute
  '/admin-media': typeof AdminMediaRoute
  '/admin-merchandising': typeof AdminMerchandisingRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-orders-ops': typeof AdminOrdersOpsRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/admin-performance': typeof AdminPerformanceRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-quality': typeof AdminQualityRoute
  '/admin-region': typeof AdminRegionRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-returns': typeof AdminReturnsRoute
  '/admin-search': typeof AdminSearchRoute
  '/admin-security': typeof AdminSecurityRoute
  '/admin-seed': typeof AdminSeedRoute
  '/admin-seo-intelligence': typeof AdminSeoIntelligenceRoute
  '/admin-shipments': typeof AdminShipmentsRoute
  '/admin-support': typeof AdminSupportRoute
  '/admin-traffic': typeof AdminTrafficRoute
  '/admin-users': typeof AdminUsersRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRouteWithChildren
  '/return': typeof ReturnRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/support': typeof AccountSupportRoute
  '/admin-customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin-product/$slug': typeof AdminProductSlugRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/seller-assistance': typeof HelpSellerAssistanceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/best-sellers': typeof ProductsBestSellersRoute
  '/products/new-arrivals': typeof ProductsNewArrivalsRoute
  '/products/trending': typeof ProductsTrendingRoute
  '/account/payment-methods/add': typeof AccountPaymentMethodsAddRoute
  '/admin-product/$slug/analytics': typeof AdminProductSlugAnalyticsRoute
  '/admin-product/$slug/details': typeof AdminProductSlugDetailsRoute
  '/admin-product/$slug/inventory': typeof AdminProductSlugInventoryRoute
  '/admin-product/$slug/merchandising': typeof AdminProductSlugMerchandisingRoute
  '/admin-product/$slug/preview': typeof AdminProductSlugPreviewRoute
  '/admin-product/$slug/pricing': typeof AdminProductSlugPricingRoute
  '/admin-product/$slug/returns': typeof AdminProductSlugReturnsRoute
  '/admin-product/$slug/seo': typeof AdminProductSlugSeoRoute
  '/admin-product/$slug/shipping': typeof AdminProductSlugShippingRoute
  '/api/public/expire-orders': typeof ApiPublicExpireOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/category/$main/$sub': typeof CategoryMainSubRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin-product/$slug/': typeof AdminProductSlugIndexRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open': typeof ApiPublicTrackOpenRoute
  '/api/public/webhooks/$courier': typeof ApiPublicWebhooksCourierRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-acquisition-intelligence': typeof AdminAcquisitionIntelligenceRoute
  '/admin-activity': typeof AdminActivityRoute
  '/admin-ai-operations': typeof AdminAiOperationsRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-badges': typeof AdminBadgesRoute
  '/admin-badges-analytics': typeof AdminBadgesAnalyticsRoute
  '/admin-badges-bulk': typeof AdminBadgesBulkRoute
  '/admin-categories': typeof AdminCategoriesRoute
  '/admin-cms': typeof AdminCmsRoute
  '/admin-customer-intelligence': typeof AdminCustomerIntelligenceRoute
  '/admin-customers': typeof AdminCustomersRouteWithChildren
  '/admin-email-delivery': typeof AdminEmailDeliveryRoute
  '/admin-email-health': typeof AdminEmailHealthRoute
  '/admin-email-ops': typeof AdminEmailOpsRoute
  '/admin-email-queue': typeof AdminEmailQueueRoute
  '/admin-emails': typeof AdminEmailsRoute
  '/admin-executive': typeof AdminExecutiveRoute
  '/admin-financial': typeof AdminFinancialRoute
  '/admin-inbox-placement': typeof AdminInboxPlacementRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-inventory-intelligence': typeof AdminInventoryIntelligenceRoute
  '/admin-live': typeof AdminLiveRoute
  '/admin-low-stock': typeof AdminLowStockRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-marketing-automation': typeof AdminMarketingAutomationRoute
  '/admin-marketing-growth': typeof AdminMarketingGrowthRoute
  '/admin-marketing-metrics': typeof AdminMarketingMetricsRoute
  '/admin-media': typeof AdminMediaRoute
  '/admin-merchandising': typeof AdminMerchandisingRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-orders-ops': typeof AdminOrdersOpsRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/admin-performance': typeof AdminPerformanceRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-quality': typeof AdminQualityRoute
  '/admin-region': typeof AdminRegionRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-returns': typeof AdminReturnsRoute
  '/admin-search': typeof AdminSearchRoute
  '/admin-security': typeof AdminSecurityRoute
  '/admin-seed': typeof AdminSeedRoute
  '/admin-seo-intelligence': typeof AdminSeoIntelligenceRoute
  '/admin-shipments': typeof AdminShipmentsRoute
  '/admin-support': typeof AdminSupportRoute
  '/admin-traffic': typeof AdminTrafficRoute
  '/admin-users': typeof AdminUsersRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRouteWithChildren
  '/return': typeof ReturnRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/support': typeof AccountSupportRoute
  '/admin-customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/seller-assistance': typeof HelpSellerAssistanceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/best-sellers': typeof ProductsBestSellersRoute
  '/products/new-arrivals': typeof ProductsNewArrivalsRoute
  '/products/trending': typeof ProductsTrendingRoute
  '/account/payment-methods/add': typeof AccountPaymentMethodsAddRoute
  '/admin-product/$slug/analytics': typeof AdminProductSlugAnalyticsRoute
  '/admin-product/$slug/details': typeof AdminProductSlugDetailsRoute
  '/admin-product/$slug/inventory': typeof AdminProductSlugInventoryRoute
  '/admin-product/$slug/merchandising': typeof AdminProductSlugMerchandisingRoute
  '/admin-product/$slug/preview': typeof AdminProductSlugPreviewRoute
  '/admin-product/$slug/pricing': typeof AdminProductSlugPricingRoute
  '/admin-product/$slug/returns': typeof AdminProductSlugReturnsRoute
  '/admin-product/$slug/seo': typeof AdminProductSlugSeoRoute
  '/admin-product/$slug/shipping': typeof AdminProductSlugShippingRoute
  '/api/public/expire-orders': typeof ApiPublicExpireOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/category/$main/$sub': typeof CategoryMainSubRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin-product/$slug': typeof AdminProductSlugIndexRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open': typeof ApiPublicTrackOpenRoute
  '/api/public/webhooks/$courier': typeof ApiPublicWebhooksCourierRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-acquisition-intelligence': typeof AdminAcquisitionIntelligenceRoute
  '/admin-activity': typeof AdminActivityRoute
  '/admin-ai-operations': typeof AdminAiOperationsRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-badges': typeof AdminBadgesRoute
  '/admin-badges-analytics': typeof AdminBadgesAnalyticsRoute
  '/admin-badges-bulk': typeof AdminBadgesBulkRoute
  '/admin-categories': typeof AdminCategoriesRoute
  '/admin-cms': typeof AdminCmsRoute
  '/admin-customer-intelligence': typeof AdminCustomerIntelligenceRoute
  '/admin-customers': typeof AdminCustomersRouteWithChildren
  '/admin-email-delivery': typeof AdminEmailDeliveryRoute
  '/admin-email-health': typeof AdminEmailHealthRoute
  '/admin-email-ops': typeof AdminEmailOpsRoute
  '/admin-email-queue': typeof AdminEmailQueueRoute
  '/admin-emails': typeof AdminEmailsRoute
  '/admin-executive': typeof AdminExecutiveRoute
  '/admin-financial': typeof AdminFinancialRoute
  '/admin-inbox-placement': typeof AdminInboxPlacementRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-inventory-intelligence': typeof AdminInventoryIntelligenceRoute
  '/admin-live': typeof AdminLiveRoute
  '/admin-low-stock': typeof AdminLowStockRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-marketing-automation': typeof AdminMarketingAutomationRoute
  '/admin-marketing-growth': typeof AdminMarketingGrowthRoute
  '/admin-marketing-metrics': typeof AdminMarketingMetricsRoute
  '/admin-media': typeof AdminMediaRoute
  '/admin-merchandising': typeof AdminMerchandisingRoute
  '/admin-notifications': typeof AdminNotificationsRoute
  '/admin-orders': typeof AdminOrdersRoute
  '/admin-orders-ops': typeof AdminOrdersOpsRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/admin-performance': typeof AdminPerformanceRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-quality': typeof AdminQualityRoute
  '/admin-region': typeof AdminRegionRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-returns': typeof AdminReturnsRoute
  '/admin-search': typeof AdminSearchRoute
  '/admin-security': typeof AdminSecurityRoute
  '/admin-seed': typeof AdminSeedRoute
  '/admin-seo-intelligence': typeof AdminSeoIntelligenceRoute
  '/admin-shipments': typeof AdminShipmentsRoute
  '/admin-support': typeof AdminSupportRoute
  '/admin-traffic': typeof AdminTrafficRoute
  '/admin-users': typeof AdminUsersRoute
  '/admin-vendors': typeof AdminVendorsRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/builder': typeof BuilderRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRouteWithChildren
  '/return': typeof ReturnRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/wishlist': typeof WishlistRoute
  '/account_/addresses': typeof AccountAddressesRoute
  '/account_/history': typeof AccountHistoryRoute
  '/account_/notifications': typeof AccountNotificationsRoute
  '/account_/orders': typeof AccountOrdersRoute
  '/account_/payments': typeof AccountPaymentsRoute
  '/account_/preferences': typeof AccountPreferencesRoute
  '/account_/profile': typeof AccountProfileRoute
  '/account_/returns': typeof AccountReturnsRoute
  '/account_/security': typeof AccountSecurityRoute
  '/account_/support': typeof AccountSupportRoute
  '/admin-customers/$customerId': typeof AdminCustomersCustomerIdRoute
  '/admin-product/$slug': typeof AdminProductSlugRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/seller-assistance': typeof HelpSellerAssistanceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/best-sellers': typeof ProductsBestSellersRoute
  '/products/new-arrivals': typeof ProductsNewArrivalsRoute
  '/products/trending': typeof ProductsTrendingRoute
  '/account_/payment-methods/add': typeof AccountPaymentMethodsAddRoute
  '/admin-product/$slug/analytics': typeof AdminProductSlugAnalyticsRoute
  '/admin-product/$slug/details': typeof AdminProductSlugDetailsRoute
  '/admin-product/$slug/inventory': typeof AdminProductSlugInventoryRoute
  '/admin-product/$slug/merchandising': typeof AdminProductSlugMerchandisingRoute
  '/admin-product/$slug/preview': typeof AdminProductSlugPreviewRoute
  '/admin-product/$slug/pricing': typeof AdminProductSlugPricingRoute
  '/admin-product/$slug/returns': typeof AdminProductSlugReturnsRoute
  '/admin-product/$slug/seo': typeof AdminProductSlugSeoRoute
  '/admin-product/$slug/shipping': typeof AdminProductSlugShippingRoute
  '/api/public/expire-orders': typeof ApiPublicExpireOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
  '/category/$main/$sub': typeof CategoryMainSubRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin-product/$slug/': typeof AdminProductSlugIndexRoute
  '/api/public/track/click': typeof ApiPublicTrackClickRoute
  '/api/public/track/open': typeof ApiPublicTrackOpenRoute
  '/api/public/webhooks/$courier': typeof ApiPublicWebhooksCourierRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-acquisition-intelligence'
    | '/admin-activity'
    | '/admin-ai-operations'
    | '/admin-analytics'
    | '/admin-badges'
    | '/admin-badges-analytics'
    | '/admin-badges-bulk'
    | '/admin-categories'
    | '/admin-cms'
    | '/admin-customer-intelligence'
    | '/admin-customers'
    | '/admin-email-delivery'
    | '/admin-email-health'
    | '/admin-email-ops'
    | '/admin-email-queue'
    | '/admin-emails'
    | '/admin-executive'
    | '/admin-financial'
    | '/admin-inbox-placement'
    | '/admin-inventory'
    | '/admin-inventory-intelligence'
    | '/admin-live'
    | '/admin-low-stock'
    | '/admin-marketing'
    | '/admin-marketing-automation'
    | '/admin-marketing-growth'
    | '/admin-marketing-metrics'
    | '/admin-media'
    | '/admin-merchandising'
    | '/admin-notifications'
    | '/admin-orders'
    | '/admin-orders-ops'
    | '/admin-payments'
    | '/admin-performance'
    | '/admin-products'
    | '/admin-quality'
    | '/admin-region'
    | '/admin-reports'
    | '/admin-returns'
    | '/admin-search'
    | '/admin-security'
    | '/admin-seed'
    | '/admin-seo-intelligence'
    | '/admin-shipments'
    | '/admin-support'
    | '/admin-traffic'
    | '/admin-users'
    | '/admin-vendors'
    | '/auth'
    | '/blog'
    | '/builder'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/compare'
    | '/deals'
    | '/help'
    | '/return'
    | '/returns'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/track'
    | '/unsubscribe'
    | '/wishlist'
    | '/account/addresses'
    | '/account/history'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/preferences'
    | '/account/profile'
    | '/account/returns'
    | '/account/security'
    | '/account/support'
    | '/admin-customers/$customerId'
    | '/admin-product/$slug'
    | '/auth/callback'
    | '/blog/$slug'
    | '/category/$slug'
    | '/email/unsubscribe'
    | '/help/seller-assistance'
    | '/orders/$id'
    | '/pages/$slug'
    | '/pages/returns'
    | '/pages/shipping'
    | '/products/$slug'
    | '/products/best-sellers'
    | '/products/new-arrivals'
    | '/products/trending'
    | '/account/payment-methods/add'
    | '/admin-product/$slug/analytics'
    | '/admin-product/$slug/details'
    | '/admin-product/$slug/inventory'
    | '/admin-product/$slug/merchandising'
    | '/admin-product/$slug/preview'
    | '/admin-product/$slug/pricing'
    | '/admin-product/$slug/returns'
    | '/admin-product/$slug/seo'
    | '/admin-product/$slug/shipping'
    | '/api/public/expire-orders'
    | '/api/public/razorpay-webhook'
    | '/category/$main/$sub'
    | '/lovable/email/suppression'
    | '/admin-product/$slug/'
    | '/api/public/track/click'
    | '/api/public/track/open'
    | '/api/public/webhooks/$courier'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-acquisition-intelligence'
    | '/admin-activity'
    | '/admin-ai-operations'
    | '/admin-analytics'
    | '/admin-badges'
    | '/admin-badges-analytics'
    | '/admin-badges-bulk'
    | '/admin-categories'
    | '/admin-cms'
    | '/admin-customer-intelligence'
    | '/admin-customers'
    | '/admin-email-delivery'
    | '/admin-email-health'
    | '/admin-email-ops'
    | '/admin-email-queue'
    | '/admin-emails'
    | '/admin-executive'
    | '/admin-financial'
    | '/admin-inbox-placement'
    | '/admin-inventory'
    | '/admin-inventory-intelligence'
    | '/admin-live'
    | '/admin-low-stock'
    | '/admin-marketing'
    | '/admin-marketing-automation'
    | '/admin-marketing-growth'
    | '/admin-marketing-metrics'
    | '/admin-media'
    | '/admin-merchandising'
    | '/admin-notifications'
    | '/admin-orders'
    | '/admin-orders-ops'
    | '/admin-payments'
    | '/admin-performance'
    | '/admin-products'
    | '/admin-quality'
    | '/admin-region'
    | '/admin-reports'
    | '/admin-returns'
    | '/admin-search'
    | '/admin-security'
    | '/admin-seed'
    | '/admin-seo-intelligence'
    | '/admin-shipments'
    | '/admin-support'
    | '/admin-traffic'
    | '/admin-users'
    | '/admin-vendors'
    | '/auth'
    | '/blog'
    | '/builder'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/compare'
    | '/deals'
    | '/help'
    | '/return'
    | '/returns'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/track'
    | '/unsubscribe'
    | '/wishlist'
    | '/account/addresses'
    | '/account/history'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/preferences'
    | '/account/profile'
    | '/account/returns'
    | '/account/security'
    | '/account/support'
    | '/admin-customers/$customerId'
    | '/auth/callback'
    | '/blog/$slug'
    | '/category/$slug'
    | '/email/unsubscribe'
    | '/help/seller-assistance'
    | '/orders/$id'
    | '/pages/$slug'
    | '/pages/returns'
    | '/pages/shipping'
    | '/products/$slug'
    | '/products/best-sellers'
    | '/products/new-arrivals'
    | '/products/trending'
    | '/account/payment-methods/add'
    | '/admin-product/$slug/analytics'
    | '/admin-product/$slug/details'
    | '/admin-product/$slug/inventory'
    | '/admin-product/$slug/merchandising'
    | '/admin-product/$slug/preview'
    | '/admin-product/$slug/pricing'
    | '/admin-product/$slug/returns'
    | '/admin-product/$slug/seo'
    | '/admin-product/$slug/shipping'
    | '/api/public/expire-orders'
    | '/api/public/razorpay-webhook'
    | '/category/$main/$sub'
    | '/lovable/email/suppression'
    | '/admin-product/$slug'
    | '/api/public/track/click'
    | '/api/public/track/open'
    | '/api/public/webhooks/$courier'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/admin-acquisition-intelligence'
    | '/admin-activity'
    | '/admin-ai-operations'
    | '/admin-analytics'
    | '/admin-badges'
    | '/admin-badges-analytics'
    | '/admin-badges-bulk'
    | '/admin-categories'
    | '/admin-cms'
    | '/admin-customer-intelligence'
    | '/admin-customers'
    | '/admin-email-delivery'
    | '/admin-email-health'
    | '/admin-email-ops'
    | '/admin-email-queue'
    | '/admin-emails'
    | '/admin-executive'
    | '/admin-financial'
    | '/admin-inbox-placement'
    | '/admin-inventory'
    | '/admin-inventory-intelligence'
    | '/admin-live'
    | '/admin-low-stock'
    | '/admin-marketing'
    | '/admin-marketing-automation'
    | '/admin-marketing-growth'
    | '/admin-marketing-metrics'
    | '/admin-media'
    | '/admin-merchandising'
    | '/admin-notifications'
    | '/admin-orders'
    | '/admin-orders-ops'
    | '/admin-payments'
    | '/admin-performance'
    | '/admin-products'
    | '/admin-quality'
    | '/admin-region'
    | '/admin-reports'
    | '/admin-returns'
    | '/admin-search'
    | '/admin-security'
    | '/admin-seed'
    | '/admin-seo-intelligence'
    | '/admin-shipments'
    | '/admin-support'
    | '/admin-traffic'
    | '/admin-users'
    | '/admin-vendors'
    | '/auth'
    | '/blog'
    | '/builder'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/compare'
    | '/deals'
    | '/help'
    | '/return'
    | '/returns'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/track'
    | '/unsubscribe'
    | '/wishlist'
    | '/account_/addresses'
    | '/account_/history'
    | '/account_/notifications'
    | '/account_/orders'
    | '/account_/payments'
    | '/account_/preferences'
    | '/account_/profile'
    | '/account_/returns'
    | '/account_/security'
    | '/account_/support'
    | '/admin-customers/$customerId'
    | '/admin-product/$slug'
    | '/auth/callback'
    | '/blog/$slug'
    | '/category/$slug'
    | '/email/unsubscribe'
    | '/help/seller-assistance'
    | '/orders/$id'
    | '/pages/$slug'
    | '/pages/returns'
    | '/pages/shipping'
    | '/products/$slug'
    | '/products/best-sellers'
    | '/products/new-arrivals'
    | '/products/trending'
    | '/account_/payment-methods/add'
    | '/admin-product/$slug/analytics'
    | '/admin-product/$slug/details'
    | '/admin-product/$slug/inventory'
    | '/admin-product/$slug/merchandising'
    | '/admin-product/$slug/preview'
    | '/admin-product/$slug/pricing'
    | '/admin-product/$slug/returns'
    | '/admin-product/$slug/seo'
    | '/admin-product/$slug/shipping'
    | '/api/public/expire-orders'
    | '/api/public/razorpay-webhook'
    | '/category/$main/$sub'
    | '/lovable/email/suppression'
    | '/admin-product/$slug/'
    | '/api/public/track/click'
    | '/api/public/track/open'
    | '/api/public/webhooks/$courier'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminAcquisitionIntelligenceRoute: typeof AdminAcquisitionIntelligenceRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAiOperationsRoute: typeof AdminAiOperationsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBadgesRoute: typeof AdminBadgesRoute
  AdminBadgesAnalyticsRoute: typeof AdminBadgesAnalyticsRoute
  AdminBadgesBulkRoute: typeof AdminBadgesBulkRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCustomerIntelligenceRoute: typeof AdminCustomerIntelligenceRoute
  AdminCustomersRoute: typeof AdminCustomersRouteWithChildren
  AdminEmailDeliveryRoute: typeof AdminEmailDeliveryRoute
  AdminEmailHealthRoute: typeof AdminEmailHealthRoute
  AdminEmailOpsRoute: typeof AdminEmailOpsRoute
  AdminEmailQueueRoute: typeof AdminEmailQueueRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminExecutiveRoute: typeof AdminExecutiveRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminInboxPlacementRoute: typeof AdminInboxPlacementRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminInventoryIntelligenceRoute: typeof AdminInventoryIntelligenceRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminLowStockRoute: typeof AdminLowStockRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminMarketingAutomationRoute: typeof AdminMarketingAutomationRoute
  AdminMarketingGrowthRoute: typeof AdminMarketingGrowthRoute
  AdminMarketingMetricsRoute: typeof AdminMarketingMetricsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminMerchandisingRoute: typeof AdminMerchandisingRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminOrdersOpsRoute: typeof AdminOrdersOpsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPerformanceRoute: typeof AdminPerformanceRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminQualityRoute: typeof AdminQualityRoute
  AdminRegionRoute: typeof AdminRegionRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminSecurityRoute: typeof AdminSecurityRoute
  AdminSeedRoute: typeof AdminSeedRoute
  AdminSeoIntelligenceRoute: typeof AdminSeoIntelligenceRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminTrafficRoute: typeof AdminTrafficRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVendorsRoute: typeof AdminVendorsRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  BuilderRoute: typeof BuilderRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  DealsRoute: typeof DealsRoute
  HelpRoute: typeof HelpRouteWithChildren
  ReturnRoute: typeof ReturnRoute
  ReturnsRoute: typeof ReturnsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  WishlistRoute: typeof WishlistRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSupportRoute: typeof AccountSupportRoute
  AdminProductSlugRoute: typeof AdminProductSlugRouteWithChildren
  CategorySlugRoute: typeof CategorySlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PagesReturnsRoute: typeof PagesReturnsRoute
  PagesShippingRoute: typeof PagesShippingRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsBestSellersRoute: typeof ProductsBestSellersRoute
  ProductsNewArrivalsRoute: typeof ProductsNewArrivalsRoute
  ProductsTrendingRoute: typeof ProductsTrendingRoute
  AccountPaymentMethodsAddRoute: typeof AccountPaymentMethodsAddRoute
  ApiPublicExpireOrdersRoute: typeof ApiPublicExpireOrdersRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
  CategoryMainSubRoute: typeof CategoryMainSubRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicTrackClickRoute: typeof ApiPublicTrackClickRoute
  ApiPublicTrackOpenRoute: typeof ApiPublicTrackOpenRoute
  ApiPublicWebhooksCourierRoute: typeof ApiPublicWebhooksCourierRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-vendors': {
      id: '/admin-vendors'
      path: '/admin-vendors'
      fullPath: '/admin-vendors'
      preLoaderRoute: typeof AdminVendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-users': {
      id: '/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-traffic': {
      id: '/admin-traffic'
      path: '/admin-traffic'
      fullPath: '/admin-traffic'
      preLoaderRoute: typeof AdminTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-support': {
      id: '/admin-support'
      path: '/admin-support'
      fullPath: '/admin-support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-shipments': {
      id: '/admin-shipments'
      path: '/admin-shipments'
      fullPath: '/admin-shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-seo-intelligence': {
      id: '/admin-seo-intelligence'
      path: '/admin-seo-intelligence'
      fullPath: '/admin-seo-intelligence'
      preLoaderRoute: typeof AdminSeoIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-seed': {
      id: '/admin-seed'
      path: '/admin-seed'
      fullPath: '/admin-seed'
      preLoaderRoute: typeof AdminSeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-security': {
      id: '/admin-security'
      path: '/admin-security'
      fullPath: '/admin-security'
      preLoaderRoute: typeof AdminSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-search': {
      id: '/admin-search'
      path: '/admin-search'
      fullPath: '/admin-search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-returns': {
      id: '/admin-returns'
      path: '/admin-returns'
      fullPath: '/admin-returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports': {
      id: '/admin-reports'
      path: '/admin-reports'
      fullPath: '/admin-reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-region': {
      id: '/admin-region'
      path: '/admin-region'
      fullPath: '/admin-region'
      preLoaderRoute: typeof AdminRegionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-quality': {
      id: '/admin-quality'
      path: '/admin-quality'
      fullPath: '/admin-quality'
      preLoaderRoute: typeof AdminQualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-products': {
      id: '/admin-products'
      path: '/admin-products'
      fullPath: '/admin-products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-performance': {
      id: '/admin-performance'
      path: '/admin-performance'
      fullPath: '/admin-performance'
      preLoaderRoute: typeof AdminPerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-payments': {
      id: '/admin-payments'
      path: '/admin-payments'
      fullPath: '/admin-payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-orders-ops': {
      id: '/admin-orders-ops'
      path: '/admin-orders-ops'
      fullPath: '/admin-orders-ops'
      preLoaderRoute: typeof AdminOrdersOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-orders': {
      id: '/admin-orders'
      path: '/admin-orders'
      fullPath: '/admin-orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-notifications': {
      id: '/admin-notifications'
      path: '/admin-notifications'
      fullPath: '/admin-notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-merchandising': {
      id: '/admin-merchandising'
      path: '/admin-merchandising'
      fullPath: '/admin-merchandising'
      preLoaderRoute: typeof AdminMerchandisingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-media': {
      id: '/admin-media'
      path: '/admin-media'
      fullPath: '/admin-media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-marketing-metrics': {
      id: '/admin-marketing-metrics'
      path: '/admin-marketing-metrics'
      fullPath: '/admin-marketing-metrics'
      preLoaderRoute: typeof AdminMarketingMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-marketing-growth': {
      id: '/admin-marketing-growth'
      path: '/admin-marketing-growth'
      fullPath: '/admin-marketing-growth'
      preLoaderRoute: typeof AdminMarketingGrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-marketing-automation': {
      id: '/admin-marketing-automation'
      path: '/admin-marketing-automation'
      fullPath: '/admin-marketing-automation'
      preLoaderRoute: typeof AdminMarketingAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-marketing': {
      id: '/admin-marketing'
      path: '/admin-marketing'
      fullPath: '/admin-marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-low-stock': {
      id: '/admin-low-stock'
      path: '/admin-low-stock'
      fullPath: '/admin-low-stock'
      preLoaderRoute: typeof AdminLowStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-live': {
      id: '/admin-live'
      path: '/admin-live'
      fullPath: '/admin-live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-inventory-intelligence': {
      id: '/admin-inventory-intelligence'
      path: '/admin-inventory-intelligence'
      fullPath: '/admin-inventory-intelligence'
      preLoaderRoute: typeof AdminInventoryIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-inventory': {
      id: '/admin-inventory'
      path: '/admin-inventory'
      fullPath: '/admin-inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-inbox-placement': {
      id: '/admin-inbox-placement'
      path: '/admin-inbox-placement'
      fullPath: '/admin-inbox-placement'
      preLoaderRoute: typeof AdminInboxPlacementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-financial': {
      id: '/admin-financial'
      path: '/admin-financial'
      fullPath: '/admin-financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-executive': {
      id: '/admin-executive'
      path: '/admin-executive'
      fullPath: '/admin-executive'
      preLoaderRoute: typeof AdminExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-emails': {
      id: '/admin-emails'
      path: '/admin-emails'
      fullPath: '/admin-emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-email-queue': {
      id: '/admin-email-queue'
      path: '/admin-email-queue'
      fullPath: '/admin-email-queue'
      preLoaderRoute: typeof AdminEmailQueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-email-ops': {
      id: '/admin-email-ops'
      path: '/admin-email-ops'
      fullPath: '/admin-email-ops'
      preLoaderRoute: typeof AdminEmailOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-email-health': {
      id: '/admin-email-health'
      path: '/admin-email-health'
      fullPath: '/admin-email-health'
      preLoaderRoute: typeof AdminEmailHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-email-delivery': {
      id: '/admin-email-delivery'
      path: '/admin-email-delivery'
      fullPath: '/admin-email-delivery'
      preLoaderRoute: typeof AdminEmailDeliveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-customers': {
      id: '/admin-customers'
      path: '/admin-customers'
      fullPath: '/admin-customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-customer-intelligence': {
      id: '/admin-customer-intelligence'
      path: '/admin-customer-intelligence'
      fullPath: '/admin-customer-intelligence'
      preLoaderRoute: typeof AdminCustomerIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-cms': {
      id: '/admin-cms'
      path: '/admin-cms'
      fullPath: '/admin-cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-categories': {
      id: '/admin-categories'
      path: '/admin-categories'
      fullPath: '/admin-categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-badges-bulk': {
      id: '/admin-badges-bulk'
      path: '/admin-badges-bulk'
      fullPath: '/admin-badges-bulk'
      preLoaderRoute: typeof AdminBadgesBulkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-badges-analytics': {
      id: '/admin-badges-analytics'
      path: '/admin-badges-analytics'
      fullPath: '/admin-badges-analytics'
      preLoaderRoute: typeof AdminBadgesAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-badges': {
      id: '/admin-badges'
      path: '/admin-badges'
      fullPath: '/admin-badges'
      preLoaderRoute: typeof AdminBadgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-analytics': {
      id: '/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-ai-operations': {
      id: '/admin-ai-operations'
      path: '/admin-ai-operations'
      fullPath: '/admin-ai-operations'
      preLoaderRoute: typeof AdminAiOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-activity': {
      id: '/admin-activity'
      path: '/admin-activity'
      fullPath: '/admin-activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-acquisition-intelligence': {
      id: '/admin-acquisition-intelligence'
      path: '/admin-acquisition-intelligence'
      fullPath: '/admin-acquisition-intelligence'
      preLoaderRoute: typeof AdminAcquisitionIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/trending': {
      id: '/products/trending'
      path: '/products/trending'
      fullPath: '/products/trending'
      preLoaderRoute: typeof ProductsTrendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/new-arrivals': {
      id: '/products/new-arrivals'
      path: '/products/new-arrivals'
      fullPath: '/products/new-arrivals'
      preLoaderRoute: typeof ProductsNewArrivalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/best-sellers': {
      id: '/products/best-sellers'
      path: '/products/best-sellers'
      fullPath: '/products/best-sellers'
      preLoaderRoute: typeof ProductsBestSellersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/shipping': {
      id: '/pages/shipping'
      path: '/pages/shipping'
      fullPath: '/pages/shipping'
      preLoaderRoute: typeof PagesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/returns': {
      id: '/pages/returns'
      path: '/pages/returns'
      fullPath: '/pages/returns'
      preLoaderRoute: typeof PagesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/seller-assistance': {
      id: '/help/seller-assistance'
      path: '/seller-assistance'
      fullPath: '/help/seller-assistance'
      preLoaderRoute: typeof HelpSellerAssistanceRouteImport
      parentRoute: typeof HelpRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/admin-product/$slug': {
      id: '/admin-product/$slug'
      path: '/admin-product/$slug'
      fullPath: '/admin-product/$slug'
      preLoaderRoute: typeof AdminProductSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-customers/$customerId': {
      id: '/admin-customers/$customerId'
      path: '/$customerId'
      fullPath: '/admin-customers/$customerId'
      preLoaderRoute: typeof AdminCustomersCustomerIdRouteImport
      parentRoute: typeof AdminCustomersRoute
    }
    '/account_/support': {
      id: '/account_/support'
      path: '/account/support'
      fullPath: '/account/support'
      preLoaderRoute: typeof AccountSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/security': {
      id: '/account_/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/returns': {
      id: '/account_/returns'
      path: '/account/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/profile': {
      id: '/account_/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/preferences': {
      id: '/account_/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/payments': {
      id: '/account_/payments'
      path: '/account/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/orders': {
      id: '/account_/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/notifications': {
      id: '/account_/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/history': {
      id: '/account_/history'
      path: '/account/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/addresses': {
      id: '/account_/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-product/$slug/': {
      id: '/admin-product/$slug/'
      path: '/'
      fullPath: '/admin-product/$slug/'
      preLoaderRoute: typeof AdminProductSlugIndexRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$main/$sub': {
      id: '/category/$main/$sub'
      path: '/category/$main/$sub'
      fullPath: '/category/$main/$sub'
      preLoaderRoute: typeof CategoryMainSubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-orders': {
      id: '/api/public/expire-orders'
      path: '/api/public/expire-orders'
      fullPath: '/api/public/expire-orders'
      preLoaderRoute: typeof ApiPublicExpireOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-product/$slug/shipping': {
      id: '/admin-product/$slug/shipping'
      path: '/shipping'
      fullPath: '/admin-product/$slug/shipping'
      preLoaderRoute: typeof AdminProductSlugShippingRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/seo': {
      id: '/admin-product/$slug/seo'
      path: '/seo'
      fullPath: '/admin-product/$slug/seo'
      preLoaderRoute: typeof AdminProductSlugSeoRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/returns': {
      id: '/admin-product/$slug/returns'
      path: '/returns'
      fullPath: '/admin-product/$slug/returns'
      preLoaderRoute: typeof AdminProductSlugReturnsRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/pricing': {
      id: '/admin-product/$slug/pricing'
      path: '/pricing'
      fullPath: '/admin-product/$slug/pricing'
      preLoaderRoute: typeof AdminProductSlugPricingRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/preview': {
      id: '/admin-product/$slug/preview'
      path: '/preview'
      fullPath: '/admin-product/$slug/preview'
      preLoaderRoute: typeof AdminProductSlugPreviewRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/merchandising': {
      id: '/admin-product/$slug/merchandising'
      path: '/merchandising'
      fullPath: '/admin-product/$slug/merchandising'
      preLoaderRoute: typeof AdminProductSlugMerchandisingRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/inventory': {
      id: '/admin-product/$slug/inventory'
      path: '/inventory'
      fullPath: '/admin-product/$slug/inventory'
      preLoaderRoute: typeof AdminProductSlugInventoryRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/details': {
      id: '/admin-product/$slug/details'
      path: '/details'
      fullPath: '/admin-product/$slug/details'
      preLoaderRoute: typeof AdminProductSlugDetailsRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/admin-product/$slug/analytics': {
      id: '/admin-product/$slug/analytics'
      path: '/analytics'
      fullPath: '/admin-product/$slug/analytics'
      preLoaderRoute: typeof AdminProductSlugAnalyticsRouteImport
      parentRoute: typeof AdminProductSlugRoute
    }
    '/account_/payment-methods/add': {
      id: '/account_/payment-methods/add'
      path: '/account/payment-methods/add'
      fullPath: '/account/payment-methods/add'
      preLoaderRoute: typeof AccountPaymentMethodsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/$courier': {
      id: '/api/public/webhooks/$courier'
      path: '/api/public/webhooks/$courier'
      fullPath: '/api/public/webhooks/$courier'
      preLoaderRoute: typeof ApiPublicWebhooksCourierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/open': {
      id: '/api/public/track/open'
      path: '/api/public/track/open'
      fullPath: '/api/public/track/open'
      preLoaderRoute: typeof ApiPublicTrackOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/track/click': {
      id: '/api/public/track/click'
      path: '/api/public/track/click'
      fullPath: '/api/public/track/click'
      preLoaderRoute: typeof ApiPublicTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminCustomersRouteChildren {
  AdminCustomersCustomerIdRoute: typeof AdminCustomersCustomerIdRoute
}

const AdminCustomersRouteChildren: AdminCustomersRouteChildren = {
  AdminCustomersCustomerIdRoute: AdminCustomersCustomerIdRoute,
}

const AdminCustomersRouteWithChildren = AdminCustomersRoute._addFileChildren(
  AdminCustomersRouteChildren,
)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface HelpRouteChildren {
  HelpSellerAssistanceRoute: typeof HelpSellerAssistanceRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSellerAssistanceRoute: HelpSellerAssistanceRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface AdminProductSlugRouteChildren {
  AdminProductSlugAnalyticsRoute: typeof AdminProductSlugAnalyticsRoute
  AdminProductSlugDetailsRoute: typeof AdminProductSlugDetailsRoute
  AdminProductSlugInventoryRoute: typeof AdminProductSlugInventoryRoute
  AdminProductSlugMerchandisingRoute: typeof AdminProductSlugMerchandisingRoute
  AdminProductSlugPreviewRoute: typeof AdminProductSlugPreviewRoute
  AdminProductSlugPricingRoute: typeof AdminProductSlugPricingRoute
  AdminProductSlugReturnsRoute: typeof AdminProductSlugReturnsRoute
  AdminProductSlugSeoRoute: typeof AdminProductSlugSeoRoute
  AdminProductSlugShippingRoute: typeof AdminProductSlugShippingRoute
  AdminProductSlugIndexRoute: typeof AdminProductSlugIndexRoute
}

const AdminProductSlugRouteChildren: AdminProductSlugRouteChildren = {
  AdminProductSlugAnalyticsRoute: AdminProductSlugAnalyticsRoute,
  AdminProductSlugDetailsRoute: AdminProductSlugDetailsRoute,
  AdminProductSlugInventoryRoute: AdminProductSlugInventoryRoute,
  AdminProductSlugMerchandisingRoute: AdminProductSlugMerchandisingRoute,
  AdminProductSlugPreviewRoute: AdminProductSlugPreviewRoute,
  AdminProductSlugPricingRoute: AdminProductSlugPricingRoute,
  AdminProductSlugReturnsRoute: AdminProductSlugReturnsRoute,
  AdminProductSlugSeoRoute: AdminProductSlugSeoRoute,
  AdminProductSlugShippingRoute: AdminProductSlugShippingRoute,
  AdminProductSlugIndexRoute: AdminProductSlugIndexRoute,
}

const AdminProductSlugRouteWithChildren =
  AdminProductSlugRoute._addFileChildren(AdminProductSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminAcquisitionIntelligenceRoute: AdminAcquisitionIntelligenceRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAiOperationsRoute: AdminAiOperationsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBadgesRoute: AdminBadgesRoute,
  AdminBadgesAnalyticsRoute: AdminBadgesAnalyticsRoute,
  AdminBadgesBulkRoute: AdminBadgesBulkRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCustomerIntelligenceRoute: AdminCustomerIntelligenceRoute,
  AdminCustomersRoute: AdminCustomersRouteWithChildren,
  AdminEmailDeliveryRoute: AdminEmailDeliveryRoute,
  AdminEmailHealthRoute: AdminEmailHealthRoute,
  AdminEmailOpsRoute: AdminEmailOpsRoute,
  AdminEmailQueueRoute: AdminEmailQueueRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminExecutiveRoute: AdminExecutiveRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminInboxPlacementRoute: AdminInboxPlacementRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminInventoryIntelligenceRoute: AdminInventoryIntelligenceRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminLowStockRoute: AdminLowStockRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminMarketingAutomationRoute: AdminMarketingAutomationRoute,
  AdminMarketingGrowthRoute: AdminMarketingGrowthRoute,
  AdminMarketingMetricsRoute: AdminMarketingMetricsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminMerchandisingRoute: AdminMerchandisingRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminOrdersOpsRoute: AdminOrdersOpsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPerformanceRoute: AdminPerformanceRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminQualityRoute: AdminQualityRoute,
  AdminRegionRoute: AdminRegionRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminSecurityRoute: AdminSecurityRoute,
  AdminSeedRoute: AdminSeedRoute,
  AdminSeoIntelligenceRoute: AdminSeoIntelligenceRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminTrafficRoute: AdminTrafficRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVendorsRoute: AdminVendorsRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  BuilderRoute: BuilderRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  DealsRoute: DealsRoute,
  HelpRoute: HelpRouteWithChildren,
  ReturnRoute: ReturnRoute,
  ReturnsRoute: ReturnsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  WishlistRoute: WishlistRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSupportRoute: AccountSupportRoute,
  AdminProductSlugRoute: AdminProductSlugRouteWithChildren,
  CategorySlugRoute: CategorySlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  OrdersIdRoute: OrdersIdRoute,
  PagesSlugRoute: PagesSlugRoute,
  PagesReturnsRoute: PagesReturnsRoute,
  PagesShippingRoute: PagesShippingRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsBestSellersRoute: ProductsBestSellersRoute,
  ProductsNewArrivalsRoute: ProductsNewArrivalsRoute,
  ProductsTrendingRoute: ProductsTrendingRoute,
  AccountPaymentMethodsAddRoute: AccountPaymentMethodsAddRoute,
  ApiPublicExpireOrdersRoute: ApiPublicExpireOrdersRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
  CategoryMainSubRoute: CategoryMainSubRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicTrackClickRoute: ApiPublicTrackClickRoute,
  ApiPublicTrackOpenRoute: ApiPublicTrackOpenRoute,
  ApiPublicWebhooksCourierRoute: ApiPublicWebhooksCourierRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
