/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TrackRouteImport } from './routes/track'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as ReturnRouteImport } from './routes/return'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DealsRouteImport } from './routes/deals'
import { Route as CompareRouteImport } from './routes/compare'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminTrafficRouteImport } from './routes/admin-traffic'
import { Route as AdminShipmentsRouteImport } from './routes/admin-shipments'
import { Route as AdminSearchRouteImport } from './routes/admin-search'
import { Route as AdminReturnsRouteImport } from './routes/admin-returns'
import { Route as AdminReportsRouteImport } from './routes/admin-reports'
import { Route as AdminProductsRouteImport } from './routes/admin-products'
import { Route as AdminPaymentsRouteImport } from './routes/admin-payments'
import { Route as AdminMarketingRouteImport } from './routes/admin-marketing'
import { Route as AdminLiveRouteImport } from './routes/admin-live'
import { Route as AdminInventoryRouteImport } from './routes/admin-inventory'
import { Route as AdminFinancialRouteImport } from './routes/admin-financial'
import { Route as AdminCustomersRouteImport } from './routes/admin-customers'
import { Route as AdminCmsRouteImport } from './routes/admin-cms'
import { Route as AdminAnalyticsRouteImport } from './routes/admin-analytics'
import { Route as AdminActivityRouteImport } from './routes/admin-activity'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PagesShippingRouteImport } from './routes/pages.shipping'
import { Route as PagesReturnsRouteImport } from './routes/pages.returns'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as OrdersIdRouteImport } from './routes/orders.$id'
import { Route as HelpSellerAssistanceRouteImport } from './routes/help.seller-assistance'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AccountSecurityRouteImport } from './routes/account_.security'
import { Route as AccountReturnsRouteImport } from './routes/account_.returns'
import { Route as AccountProfileRouteImport } from './routes/account_.profile'
import { Route as AccountPreferencesRouteImport } from './routes/account_.preferences'
import { Route as AccountPaymentsRouteImport } from './routes/account_.payments'
import { Route as AccountOrdersRouteImport } from './routes/account_.orders'
import { Route as AccountNotificationsRouteImport } from './routes/account_.notifications'
import { Route as AccountHistoryRouteImport } from './routes/account_.history'
import { Route as AccountAddressesRouteImport } from './routes/account_.addresses'
import { Route as ApiPublicRazorpayWebhookRouteImport } from './routes/api/public/razorpay-webhook'
import { Route as ApiPublicExpireOrdersRouteImport } from './routes/api/public/expire-orders'
import { Route as AccountPaymentMethodsAddRouteImport } from './routes/account_.payment-methods.add'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnRoute = ReturnRouteImport.update({
  id: '/return',
  path: '/return',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DealsRoute = DealsRouteImport.update({
  id: '/deals',
  path: '/deals',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRoute = CompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTrafficRoute = AdminTrafficRouteImport.update({
  id: '/admin-traffic',
  path: '/admin-traffic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminShipmentsRoute = AdminShipmentsRouteImport.update({
  id: '/admin-shipments',
  path: '/admin-shipments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSearchRoute = AdminSearchRouteImport.update({
  id: '/admin-search',
  path: '/admin-search',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReturnsRoute = AdminReturnsRouteImport.update({
  id: '/admin-returns',
  path: '/admin-returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin-reports',
  path: '/admin-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin-products',
  path: '/admin-products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin-payments',
  path: '/admin-payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/admin-marketing',
  path: '/admin-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/admin-live',
  path: '/admin-live',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/admin-inventory',
  path: '/admin-inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinancialRoute = AdminFinancialRouteImport.update({
  id: '/admin-financial',
  path: '/admin-financial',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin-customers',
  path: '/admin-customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCmsRoute = AdminCmsRouteImport.update({
  id: '/admin-cms',
  path: '/admin-cms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin-analytics',
  path: '/admin-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/admin-activity',
  path: '/admin-activity',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesShippingRoute = PagesShippingRouteImport.update({
  id: '/pages/shipping',
  path: '/pages/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesReturnsRoute = PagesReturnsRouteImport.update({
  id: '/pages/returns',
  path: '/pages/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersIdRoute = OrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpSellerAssistanceRoute = HelpSellerAssistanceRouteImport.update({
  id: '/seller-assistance',
  path: '/seller-assistance',
  getParentRoute: () => HelpRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/account_/security',
  path: '/account/security',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountReturnsRoute = AccountReturnsRouteImport.update({
  id: '/account_/returns',
  path: '/account/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/account_/profile',
  path: '/account/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/account_/preferences',
  path: '/account/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPaymentsRoute = AccountPaymentsRouteImport.update({
  id: '/account_/payments',
  path: '/account/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountOrdersRoute = AccountOrdersRouteImport.update({
  id: '/account_/orders',
  path: '/account/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/account_/notifications',
  path: '/account/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountHistoryRoute = AccountHistoryRouteImport.update({
  id: '/account_/history',
  path: '/account/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAddressesRoute = AccountAddressesRouteImport.update({
  id: '/account_/addresses',
  path: '/account/addresses',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRazorpayWebhookRoute =
  ApiPublicRazorpayWebhookRouteImport.update({
    id: '/api/public/razorpay-webhook',
    path: '/api/public/razorpay-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicExpireOrdersRoute = ApiPublicExpireOrdersRouteImport.update({
  id: '/api/public/expire-orders',
  path: '/api/public/expire-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountPaymentMethodsAddRoute =
  AccountPaymentMethodsAddRouteImport.update({
    id: '/account_/payment-methods/add',
    path: '/account/payment-methods/add',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-activity': typeof AdminActivityRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-cms': typeof AdminCmsRoute
  '/admin-customers': typeof AdminCustomersRoute
  '/admin-financial': typeof AdminFinancialRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-live': typeof AdminLiveRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-returns': typeof AdminReturnsRoute
  '/admin-search': typeof AdminSearchRoute
  '/admin-shipments': typeof AdminShipmentsRoute
  '/admin-traffic': typeof AdminTrafficRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRouteWithChildren
  '/return': typeof ReturnRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/help/seller-assistance': typeof HelpSellerAssistanceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/payment-methods/add': typeof AccountPaymentMethodsAddRoute
  '/api/public/expire-orders': typeof ApiPublicExpireOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-activity': typeof AdminActivityRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-cms': typeof AdminCmsRoute
  '/admin-customers': typeof AdminCustomersRoute
  '/admin-financial': typeof AdminFinancialRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-live': typeof AdminLiveRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-returns': typeof AdminReturnsRoute
  '/admin-search': typeof AdminSearchRoute
  '/admin-shipments': typeof AdminShipmentsRoute
  '/admin-traffic': typeof AdminTrafficRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRouteWithChildren
  '/return': typeof ReturnRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/account/addresses': typeof AccountAddressesRoute
  '/account/history': typeof AccountHistoryRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/orders': typeof AccountOrdersRoute
  '/account/payments': typeof AccountPaymentsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/profile': typeof AccountProfileRoute
  '/account/returns': typeof AccountReturnsRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/help/seller-assistance': typeof HelpSellerAssistanceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account/payment-methods/add': typeof AccountPaymentMethodsAddRoute
  '/api/public/expire-orders': typeof ApiPublicExpireOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/admin-activity': typeof AdminActivityRoute
  '/admin-analytics': typeof AdminAnalyticsRoute
  '/admin-cms': typeof AdminCmsRoute
  '/admin-customers': typeof AdminCustomersRoute
  '/admin-financial': typeof AdminFinancialRoute
  '/admin-inventory': typeof AdminInventoryRoute
  '/admin-live': typeof AdminLiveRoute
  '/admin-marketing': typeof AdminMarketingRoute
  '/admin-payments': typeof AdminPaymentsRoute
  '/admin-products': typeof AdminProductsRoute
  '/admin-reports': typeof AdminReportsRoute
  '/admin-returns': typeof AdminReturnsRoute
  '/admin-search': typeof AdminSearchRoute
  '/admin-shipments': typeof AdminShipmentsRoute
  '/admin-traffic': typeof AdminTrafficRoute
  '/auth': typeof AuthRouteWithChildren
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/compare': typeof CompareRoute
  '/deals': typeof DealsRoute
  '/help': typeof HelpRouteWithChildren
  '/return': typeof ReturnRoute
  '/returns': typeof ReturnsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/track': typeof TrackRoute
  '/wishlist': typeof WishlistRoute
  '/account_/addresses': typeof AccountAddressesRoute
  '/account_/history': typeof AccountHistoryRoute
  '/account_/notifications': typeof AccountNotificationsRoute
  '/account_/orders': typeof AccountOrdersRoute
  '/account_/payments': typeof AccountPaymentsRoute
  '/account_/preferences': typeof AccountPreferencesRoute
  '/account_/profile': typeof AccountProfileRoute
  '/account_/returns': typeof AccountReturnsRoute
  '/account_/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/category/$slug': typeof CategorySlugRoute
  '/help/seller-assistance': typeof HelpSellerAssistanceRoute
  '/orders/$id': typeof OrdersIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/pages/returns': typeof PagesReturnsRoute
  '/pages/shipping': typeof PagesShippingRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/account_/payment-methods/add': typeof AccountPaymentMethodsAddRoute
  '/api/public/expire-orders': typeof ApiPublicExpireOrdersRoute
  '/api/public/razorpay-webhook': typeof ApiPublicRazorpayWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-activity'
    | '/admin-analytics'
    | '/admin-cms'
    | '/admin-customers'
    | '/admin-financial'
    | '/admin-inventory'
    | '/admin-live'
    | '/admin-marketing'
    | '/admin-payments'
    | '/admin-products'
    | '/admin-reports'
    | '/admin-returns'
    | '/admin-search'
    | '/admin-shipments'
    | '/admin-traffic'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/deals'
    | '/help'
    | '/return'
    | '/returns'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/track'
    | '/wishlist'
    | '/account/addresses'
    | '/account/history'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/preferences'
    | '/account/profile'
    | '/account/returns'
    | '/account/security'
    | '/auth/callback'
    | '/blog/$slug'
    | '/category/$slug'
    | '/help/seller-assistance'
    | '/orders/$id'
    | '/pages/$slug'
    | '/pages/returns'
    | '/pages/shipping'
    | '/products/$slug'
    | '/account/payment-methods/add'
    | '/api/public/expire-orders'
    | '/api/public/razorpay-webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/admin-activity'
    | '/admin-analytics'
    | '/admin-cms'
    | '/admin-customers'
    | '/admin-financial'
    | '/admin-inventory'
    | '/admin-live'
    | '/admin-marketing'
    | '/admin-payments'
    | '/admin-products'
    | '/admin-reports'
    | '/admin-returns'
    | '/admin-search'
    | '/admin-shipments'
    | '/admin-traffic'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/deals'
    | '/help'
    | '/return'
    | '/returns'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/track'
    | '/wishlist'
    | '/account/addresses'
    | '/account/history'
    | '/account/notifications'
    | '/account/orders'
    | '/account/payments'
    | '/account/preferences'
    | '/account/profile'
    | '/account/returns'
    | '/account/security'
    | '/auth/callback'
    | '/blog/$slug'
    | '/category/$slug'
    | '/help/seller-assistance'
    | '/orders/$id'
    | '/pages/$slug'
    | '/pages/returns'
    | '/pages/shipping'
    | '/products/$slug'
    | '/account/payment-methods/add'
    | '/api/public/expire-orders'
    | '/api/public/razorpay-webhook'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/admin-activity'
    | '/admin-analytics'
    | '/admin-cms'
    | '/admin-customers'
    | '/admin-financial'
    | '/admin-inventory'
    | '/admin-live'
    | '/admin-marketing'
    | '/admin-payments'
    | '/admin-products'
    | '/admin-reports'
    | '/admin-returns'
    | '/admin-search'
    | '/admin-shipments'
    | '/admin-traffic'
    | '/auth'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/compare'
    | '/deals'
    | '/help'
    | '/return'
    | '/returns'
    | '/robots.txt'
    | '/search'
    | '/sitemap.xml'
    | '/track'
    | '/wishlist'
    | '/account_/addresses'
    | '/account_/history'
    | '/account_/notifications'
    | '/account_/orders'
    | '/account_/payments'
    | '/account_/preferences'
    | '/account_/profile'
    | '/account_/returns'
    | '/account_/security'
    | '/auth/callback'
    | '/blog/$slug'
    | '/category/$slug'
    | '/help/seller-assistance'
    | '/orders/$id'
    | '/pages/$slug'
    | '/pages/returns'
    | '/pages/shipping'
    | '/products/$slug'
    | '/account_/payment-methods/add'
    | '/api/public/expire-orders'
    | '/api/public/razorpay-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  AdminActivityRoute: typeof AdminActivityRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCmsRoute: typeof AdminCmsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminFinancialRoute: typeof AdminFinancialRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminLiveRoute: typeof AdminLiveRoute
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReturnsRoute: typeof AdminReturnsRoute
  AdminSearchRoute: typeof AdminSearchRoute
  AdminShipmentsRoute: typeof AdminShipmentsRoute
  AdminTrafficRoute: typeof AdminTrafficRoute
  AuthRoute: typeof AuthRouteWithChildren
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CompareRoute: typeof CompareRoute
  DealsRoute: typeof DealsRoute
  HelpRoute: typeof HelpRouteWithChildren
  ReturnRoute: typeof ReturnRoute
  ReturnsRoute: typeof ReturnsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrackRoute: typeof TrackRoute
  WishlistRoute: typeof WishlistRoute
  AccountAddressesRoute: typeof AccountAddressesRoute
  AccountHistoryRoute: typeof AccountHistoryRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountOrdersRoute: typeof AccountOrdersRoute
  AccountPaymentsRoute: typeof AccountPaymentsRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountProfileRoute: typeof AccountProfileRoute
  AccountReturnsRoute: typeof AccountReturnsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  CategorySlugRoute: typeof CategorySlugRoute
  OrdersIdRoute: typeof OrdersIdRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PagesReturnsRoute: typeof PagesReturnsRoute
  PagesShippingRoute: typeof PagesShippingRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  AccountPaymentMethodsAddRoute: typeof AccountPaymentMethodsAddRoute
  ApiPublicExpireOrdersRoute: typeof ApiPublicExpireOrdersRoute
  ApiPublicRazorpayWebhookRoute: typeof ApiPublicRazorpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/return': {
      id: '/return'
      path: '/return'
      fullPath: '/return'
      preLoaderRoute: typeof ReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deals': {
      id: '/deals'
      path: '/deals'
      fullPath: '/deals'
      preLoaderRoute: typeof DealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-traffic': {
      id: '/admin-traffic'
      path: '/admin-traffic'
      fullPath: '/admin-traffic'
      preLoaderRoute: typeof AdminTrafficRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-shipments': {
      id: '/admin-shipments'
      path: '/admin-shipments'
      fullPath: '/admin-shipments'
      preLoaderRoute: typeof AdminShipmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-search': {
      id: '/admin-search'
      path: '/admin-search'
      fullPath: '/admin-search'
      preLoaderRoute: typeof AdminSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-returns': {
      id: '/admin-returns'
      path: '/admin-returns'
      fullPath: '/admin-returns'
      preLoaderRoute: typeof AdminReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-reports': {
      id: '/admin-reports'
      path: '/admin-reports'
      fullPath: '/admin-reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-products': {
      id: '/admin-products'
      path: '/admin-products'
      fullPath: '/admin-products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-payments': {
      id: '/admin-payments'
      path: '/admin-payments'
      fullPath: '/admin-payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-marketing': {
      id: '/admin-marketing'
      path: '/admin-marketing'
      fullPath: '/admin-marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-live': {
      id: '/admin-live'
      path: '/admin-live'
      fullPath: '/admin-live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-inventory': {
      id: '/admin-inventory'
      path: '/admin-inventory'
      fullPath: '/admin-inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-financial': {
      id: '/admin-financial'
      path: '/admin-financial'
      fullPath: '/admin-financial'
      preLoaderRoute: typeof AdminFinancialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-customers': {
      id: '/admin-customers'
      path: '/admin-customers'
      fullPath: '/admin-customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-cms': {
      id: '/admin-cms'
      path: '/admin-cms'
      fullPath: '/admin-cms'
      preLoaderRoute: typeof AdminCmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-analytics': {
      id: '/admin-analytics'
      path: '/admin-analytics'
      fullPath: '/admin-analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-activity': {
      id: '/admin-activity'
      path: '/admin-activity'
      fullPath: '/admin-activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/shipping': {
      id: '/pages/shipping'
      path: '/pages/shipping'
      fullPath: '/pages/shipping'
      preLoaderRoute: typeof PagesShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/returns': {
      id: '/pages/returns'
      path: '/pages/returns'
      fullPath: '/pages/returns'
      preLoaderRoute: typeof PagesReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders/$id': {
      id: '/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof OrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/seller-assistance': {
      id: '/help/seller-assistance'
      path: '/seller-assistance'
      fullPath: '/help/seller-assistance'
      preLoaderRoute: typeof HelpSellerAssistanceRouteImport
      parentRoute: typeof HelpRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/account_/security': {
      id: '/account_/security'
      path: '/account/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/returns': {
      id: '/account_/returns'
      path: '/account/returns'
      fullPath: '/account/returns'
      preLoaderRoute: typeof AccountReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/profile': {
      id: '/account_/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/preferences': {
      id: '/account_/preferences'
      path: '/account/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/payments': {
      id: '/account_/payments'
      path: '/account/payments'
      fullPath: '/account/payments'
      preLoaderRoute: typeof AccountPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/orders': {
      id: '/account_/orders'
      path: '/account/orders'
      fullPath: '/account/orders'
      preLoaderRoute: typeof AccountOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/notifications': {
      id: '/account_/notifications'
      path: '/account/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/history': {
      id: '/account_/history'
      path: '/account/history'
      fullPath: '/account/history'
      preLoaderRoute: typeof AccountHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/addresses': {
      id: '/account_/addresses'
      path: '/account/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AccountAddressesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/razorpay-webhook': {
      id: '/api/public/razorpay-webhook'
      path: '/api/public/razorpay-webhook'
      fullPath: '/api/public/razorpay-webhook'
      preLoaderRoute: typeof ApiPublicRazorpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/expire-orders': {
      id: '/api/public/expire-orders'
      path: '/api/public/expire-orders'
      fullPath: '/api/public/expire-orders'
      preLoaderRoute: typeof ApiPublicExpireOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account_/payment-methods/add': {
      id: '/account_/payment-methods/add'
      path: '/account/payment-methods/add'
      fullPath: '/account/payment-methods/add'
      preLoaderRoute: typeof AccountPaymentMethodsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface HelpRouteChildren {
  HelpSellerAssistanceRoute: typeof HelpSellerAssistanceRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpSellerAssistanceRoute: HelpSellerAssistanceRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  AdminActivityRoute: AdminActivityRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCmsRoute: AdminCmsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminFinancialRoute: AdminFinancialRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminLiveRoute: AdminLiveRoute,
  AdminMarketingRoute: AdminMarketingRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReturnsRoute: AdminReturnsRoute,
  AdminSearchRoute: AdminSearchRoute,
  AdminShipmentsRoute: AdminShipmentsRoute,
  AdminTrafficRoute: AdminTrafficRoute,
  AuthRoute: AuthRouteWithChildren,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CompareRoute: CompareRoute,
  DealsRoute: DealsRoute,
  HelpRoute: HelpRouteWithChildren,
  ReturnRoute: ReturnRoute,
  ReturnsRoute: ReturnsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrackRoute: TrackRoute,
  WishlistRoute: WishlistRoute,
  AccountAddressesRoute: AccountAddressesRoute,
  AccountHistoryRoute: AccountHistoryRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountOrdersRoute: AccountOrdersRoute,
  AccountPaymentsRoute: AccountPaymentsRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountProfileRoute: AccountProfileRoute,
  AccountReturnsRoute: AccountReturnsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  CategorySlugRoute: CategorySlugRoute,
  OrdersIdRoute: OrdersIdRoute,
  PagesSlugRoute: PagesSlugRoute,
  PagesReturnsRoute: PagesReturnsRoute,
  PagesShippingRoute: PagesShippingRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  AccountPaymentMethodsAddRoute: AccountPaymentMethodsAddRoute,
  ApiPublicExpireOrdersRoute: ApiPublicExpireOrdersRoute,
  ApiPublicRazorpayWebhookRoute: ApiPublicRazorpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
